[package]
name = "thombruce"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
drizzle-css = "=0.1.4"
include_dir = "0.7.4"
maud = { version = "0.27.0", features = ["axum"] }
pulldown-cmark = "0.13.4"
rand = "0.10.2"
russh = "0.62.5"
tokio = { version = "1.53.1", features = ["full"] }

[lints.clippy]
# UM, ACTUALLY
pedantic = { level = "warn", priority = -1 }
# DEVELOPING LINTS
nursery = { level = "warn", priority = -1 }
# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
