# fly.toml app configuration file generated for thombruce on 2026-08-01T15:44:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thombruce'
primary_region = 'lhr'

[build]
[env]
  PORT = '3000'
  SSH_PORT = '2222'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 22

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
